item {
    id: 1
    name: 'apple'
}

item {
    id: 2
    name: 'banana'
}

item {
    id: 3
    name: 'strawberry'
}

item {
    id: 4
    name: 'broccoli'
}

item {
    id: 5
    name: 'blueberry'
}

item {
    id: 6
    name: 'potatoes'
}

item {
    id: 7
    name: 'egg'
}

item {
    id: 8
    name: 'bread'
}

item {
    id: 9
    name: 'milk'
}

item {
    id: 10
    name: 'avocado'
}

item {
    id: 11
    name: 'orange'
}

item {
    id: 12
    name: 'tomatoes'
}